Connect via unix socket instead of filesystem to be compatible with php open_basedir restrictions.
pantheon-systems/wp-redis pull request #426
Opened 2023-05-30 14:44 UTC by jazzsequence

copied from #425 to run CI workflows by @hj-collab

Behat fixes ported to https://github.com/pantheon-systems/wp-redis/pull/429/

2023-06-05 20:00 UTC, pwtyler submitted a review, later dismissed

2023-06-06 22:29 UTC, pwtyler requested changes
Need to update README (c/f #423)

2023-06-08 21:42 UTC, jazzsequence commented on tests/behat/features/load-wp.feature
> +	When I wait "1" second
spacing
```suggestion
    When I wait "1" second
```

2023-06-08 21:42 UTC, jazzsequence commented on tests/behat/features/wp-redis.feature
> +	Then I should see "Group:"
more spacing issues

2023-08-14 22:45 UTC, pwtyler commented
This PR ended up all over the place and ultimately derailed on the testing. Going to close and re-open the original PR (although we still need to prioritize the work on the teamside). As we've learned since this was attempted, pushing fork PRs to a separate branch (rather than opening a new PR) stills gives us the circle checks in the original PR. 

Better/cleaner would be to move all tests to Github actions triggered "On PR", which can be approved by a codeowner to run CI after manually reviewing.

2023-08-14 22:45 UTC, closed without merging