Adjust CONTRIBUTING Guidelines
pantheon-systems/wp-redis pull request #427
Opened 2023-06-01 17:17 UTC by pwtyler

- Replace `master` with `release`
- More explicit steps for prepare-dev commands
- Drop latest heading in favor of -dev build heading in changelogs

2023-06-05 15:25 UTC, jazzsequence requested changes

2023-06-05 15:25 UTC, jazzsequence commented on CONTRIBUTING.md
> +	 * `git checkout develop`
need to change `develop` to `default`
spacing is weird here

2023-06-05 21:40 UTC, pwtyler commented on CONTRIBUTING.md
> +    * In `README.md`, `readme.txt`, and `wp-redis.php`, remove the `-dev` from the version number.
```suggestion
    * In `README.md`, `readme.txt`, and `wp-redis.php`, remove the `-dev` from the version number. For the README files. the version number must be updated both at the top of the document as well as the changelog.
```

2023-06-05 21:42 UTC, pwtyler commented on CONTRIBUTING.md
> +    * `git rebase release`
```suggestion
    * `git checkout release`
    * `git pull origin release`
    * `git checkout default`
    * `git rebase release`
```

2023-06-06 21:52 UTC, jazzsequence approved these changes

2023-06-06 22:14 UTC, pwtyler commented
Behat being addressed elsewhere.

2023-06-06 22:14 UTC, merged